// names.js - Mother's Assistant Baby Names Database

const babyNames = [
    // ගැහැණු නම් (Girls)
    { id: 1, name: 'අභිෂේකා', meaning: 'අභිෂේක ලත්, පූජනීය වූ තැනැත්තිය', gender: 'girl' },
    { id: 2, name: 'අමායා', meaning: 'නිර්මල වූ, රැවටීමක් නොමැති ආලෝකය', gender: 'girl' },
    { id: 3, name: 'කාව්‍යා', meaning: 'කවියක් බඳු වූ, කලාත්මක සුන්දරත්වය', gender: 'girl' },
    { id: 4, name: 'දිනුලි', meaning: 'ජයග්‍රාහී ආලෝකය පතුරුවන මනාලිය', gender: 'girl' },
    { id: 5, name: 'දෙව්මිණි', meaning: 'දෙවියන් දුන් මැණිකක් වැනි වටිනා', gender: 'girl' },
    { id: 6, name: 'නෙත්මිණි', meaning: 'ඇසක් වැනි වටිනා මැණික', gender: 'girl' },
    { id: 7, name: 'මල්ෂා', meaning: 'මලක් මෙන් සුන්දර සහ සුවඳවත්', gender: 'girl' },
    { id: 8, name: 'සහස්‍රා', meaning: 'දහසක් කිරණ විහිදුවන සූර්යයා මෙන්', gender: 'girl' },
    { id: 9, name: 'විහාරා', meaning: 'ශාන්ත වූ, නිදහස් මනසක් ඇති', gender: 'girl' },
    { id: 10, name: 'තාරුකා', meaning: 'අහසේ දිලිසෙන තරුවක් වැනි', gender: 'girl' },
    { id: 11, name: 'භාග්‍යා', meaning: 'වාසනාවන්ත, පිනැති තැනැත්තිය', gender: 'girl' },
    { id: 12, name: 'හිරුනි', meaning: 'සූර්යයා මෙන් බැබළෙන දියණිය', gender: 'girl' },
    { id: 13, name: 'අමන්දා', meaning: 'අමා වැනි, ප්‍රියමනාප වූ', gender: 'girl' },
    { id: 14, name: 'චෙනුලි', meaning: 'සඳක් මෙන් සුන්දර, සිත්ගන්නා සුළු', gender: 'girl' },
    { id: 15, name: 'සෙනුරි', meaning: 'ආදරණීය, කරුණාවන්ත දියණිය', gender: 'girl' },
    { id: 16, name: 'යෙනුලි', meaning: 'ඥානවන්ත, බුද්ධිමත් දැරිය', gender: 'girl' },
    { id: 17, name: 'ඕෂධී', meaning: 'ඖෂධයක් වැනි, සුවය ගෙනෙන', gender: 'girl' },
    { id: 18, name: 'පවනි', meaning: 'පිරිසිදු, සුළඟක් මෙන් සැහැල්ලු', gender: 'girl' },
    { id: 19, name: 'රුසඳි', meaning: 'රූමත්, සඳක් වැනි', gender: 'girl' },
    { id: 20, name: 'තිසාරි', meaning: 'සතුටුදායක, ප්‍රීතිමත් තැනැත්තිය', gender: 'girl' },
    { id: 21, name: 'නුතාරා', meaning: 'අලුත් තරුවක් මෙන් බැබළෙන', gender: 'girl' },
    { id: 22, name: 'මියුමි', meaning: 'මිහිරි හඬක් ඇති, සංගීතකාමී', gender: 'girl' },
    { id: 23, name: 'රන්දි', meaning: 'රත්තරන් මෙන් වටිනා', gender: 'girl' },
    { id: 24, name: 'හසිනි', meaning: 'සිනහවෙන් පිරි, ප්‍රීතිමත්', gender: 'girl' },
    { id: 25, name: 'ලෝචනා', meaning: 'සුන්දර නෙත් ඇති තැනැත්තිය', gender: 'girl' },

    // පිරිමි නම් (Boys)
    { id: 26, name: 'අසංක', meaning: 'සැකයක් නොමැති, ස්ථිර ගති ඇති', gender: 'boy' },
    { id: 27, name: 'අනුත්තර', meaning: 'සියල්ලටම වඩා උතුම් වූ, අග්‍රගණ්‍ය', gender: 'boy' },
    { id: 28, name: 'කල්පන', meaning: 'සිතුවිලි බහුල, නිර්මාණශීලී බුද්ධිය', gender: 'boy' },
    { id: 29, name: 'කසුන්', meaning: 'රත්තරන් වැනි වටිනා, දීප්තිමත්', gender: 'boy' },
    { id: 30, name: 'කෙලුම්', meaning: 'කීර්තිය පතුරුවන, වාසනාවන්ත', gender: 'boy' },
    { id: 31, name: 'නිනුක', meaning: 'නිවැරදි දැක්මක් ඇති, බුද්ධිමත්', gender: 'boy' },
    { id: 32, name: 'මිනුක', meaning: 'පැහැදිලි නෙත් ඇති, ඥානවන්ත පැටියා', gender: 'boy' },
    { id: 33, name: 'ප්‍රවීන්', meaning: 'දක්ෂ, ඕනෑම දෙයකට ශූර වූ', gender: 'boy' },
    { id: 34, name: 'පබසර', meaning: 'දිලිසෙන සුලු, මනරම් ආලෝකය', gender: 'boy' },
    { id: 35, name: 'සෙනුර', meaning: 'ලස්සන, කාටත් ප්‍රියමනාප නායකයෙක්', gender: 'boy' },
    { id: 36, name: 'විනුක', meaning: 'විනයගරුක, යහපත් ගතිගුණ ඇති', gender: 'boy' },
    { id: 37, name: 'ගිහාන්', meaning: 'විශ්වය, ලෝකය ජයගන්නා', gender: 'boy' },
    { id: 38, name: 'චතුර', meaning: 'කතා කිරීමට දක්ෂ, ඥානාන්විත', gender: 'boy' },
    { id: 39, name: 'ජනන', meaning: 'උපත දෙන, ජීවය ලබාදෙන', gender: 'boy' },
    { id: 40, name: 'යොෂිත', meaning: 'සැප සම්පත් ඇති, වාසනාවන්ත', gender: 'boy' },
    { id: 41, name: 'රවිඳු', meaning: 'සූර්යයා සහ චන්ද්‍රයා වැනි දීප්තිමත්', gender: 'boy' },
    { id: 42, name: 'ලක්මාල්', meaning: 'ශ්‍රී ලංකාවේ මලක් බඳු වටිනා', gender: 'boy' },
    { id: 43, name: 'සහන්', meaning: 'සැනසීම ගෙන දෙන, නිවහල්', gender: 'boy' },
    { id: 44, name: 'අකිල', meaning: 'සම්පූර්ණ වූ, නොකැඩුණු', gender: 'boy' },
    { id: 45, name: 'යෙනුක', meaning: 'බුද්ධිමත්, තීක්ෂණ නුවණක් ඇති', gender: 'boy' },
    { id: 46, name: 'සදීව්', meaning: 'සදාකාලික ජීවයක් වැනි', gender: 'boy' },
    { id: 47, name: 'මෙතුන්', meaning: 'මිත්‍රශීලී, කාරුණික', gender: 'boy' },
    { id: 48, name: 'රුවින්', meaning: 'රූමත්, කඩවසම් පෙනුමක් ඇති', gender: 'boy' },
    { id: 49, name: 'හිරුක', meaning: 'හිරු මෙන් දීප්තිමත්', gender: 'boy' },
    { id: 50, name: 'නුසර', meaning: 'නිර්මාණශීලී, අලුත් දේවල් හොයන', gender: 'boy' }
];